import{a as m,i as p,S as v}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const d=()=>{const t=document.querySelector(".loader");t&&t.remove()},q="42275750-ff2dba3de74b1266fbd0f53be";async function y(t,o){const s=new URLSearchParams({key:q,q:t,image_type:"photo",per_page:15,page:o});m.defaults.baseURL="https://pixabay.com";const a="/api/";return await m.get(a,{params:s}).then(e=>{if(e.data.totalHits===0)d(),p.error({position:"topRight",color:"red",message:"Sorry, there are no images matching<br>your search query. Please try again!"});else return e.data})}const P=document.querySelector(".gallery");function E(t){const{largeImageURL:o,webformatURL:s,tags:a,likes:e,views:r,comments:n,downloads:w}=t;return`<li class="gallery-item">
          <a class="gallery-link" href="${o}">
            <img class="gallery-image" src="${s}" alt="${a}"/>
          </a>
          <div>
            <p><b>Likes </b>${e}</p>
            <p><b>Views </b>${r}</p>
            <p><b>Comments </b>${n}</p>
            <p><b>Downloads </b>${w}</p>
          </div>
        </li>
      `}function f(t){const o=t.map(E).join("");P.insertAdjacentHTML("beforeend",o)}const u=document.querySelector("#form");document.querySelector(".button");const g=document.querySelector(".gallery"),R=document.querySelector(".block"),i=document.querySelector(".btn"),$={captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionSelector:"img",captionDelay:250};let l,c,h,b=new v(".gallery a",$);i.style.display="none";const L=()=>{const t=document.createElement("span");t.classList.add("loader"),t.textContent="Loading images, please wait...",R.append(t)};u.addEventListener("submit",x);i.addEventListener("click",O);async function x(t){t.preventDefault(),i.style.display="none",g.innerHTML="",c=u.elements.query.value.trim(),l=1;try{const o=await y(c,l);h=Math.ceil(o.totalHits/15),c===""?(d(),p.error({position:"topRight",color:"red",message:"Sorry, there are no images matching<br>your search query. Please try again!"})):(L(),f(o.hits),b.refresh(),S())}catch(o){console.log("Error fetching data:",o)}u.reset(),d()}async function O(){L(),l+=1;const t=await y(c,l);f(t.hits),d(),S();const o=g.firstElementChild.getBoundingClientRect().height;scrollBy({top:o*2,left:0,behavior:"smooth"}),b.refresh()}function S(){l>=h?(i.style.display="none",p.info({position:"topRight",overlay:!1,color:"blue",message:"We're sorry, but you've reached the end of search results."})):i.style.display="block"}
//# sourceMappingURL=commonHelpers.js.map
